#!/usr/bin/env bash

nagbar_on() {
    swaynag -t warning -m 'Session Management' -B 'Power Down' 'systemctl poweroff' -B 'Suspend' 'systemctl suspend' -B 'Logout' 'i3-msg exit' &
}

nagbar_off() {
    pkill swaynag
}

if pgrep swaynag; then
    nagbar_off
else
    nagbar_on
fi
