# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"rust" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"thunderbird" = ""
"slack" = ""
"nemo" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"nvim" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"deluge" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"spotify" = ""
"disk usage" = ""
"zathura" = ""
"telegram" = ""
"pycharm" = ""
"jellyfin media player" = ""

[other]
fallback_icon = ""
deduplicate_icons = true
