# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"shell" = ""

"private browsing" = ""
"firefox" = ""
"chrome" = ""
"brave" = ""

"thunderbird" = ""
"mail" = ""

"slack" = ""
"telegram" = ""
"discord" = "ﭮ"
"zoom" = ""
"microsoft teams" = ""
"whatsapp" = ""

"nemo" = ""
"file manager" = ""
"disk usage" = ""
"menu" = ""
"calculator" = ""
"keepassxc" = ""
"bluetooth" = ""

"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""

"transmission" = ""
"deluge" = ""
"torrent" = ""

"mpv" = ""
"spotify" = ""
"spot" = ""
"music" = ""
"jellyfin media player" = ""

"zathura" = ""
"xournal" = ""
"pycharm" = ""
"python" = ""
"rust" = ""

"gimp" = ""
"inkscape" = ""

"steam" = ""

[other]
fallback_icon = ""
deduplicate_icons = true
