#!/usr/bin/env bash

if [ ! -z "$(which light-locker-command)" ]; then
    light-locker-command --lock
elif [ ! -z "$(which cinnamon-screensaver-command)" ]; then
    cinnamon-screensaver-command --lock
else
    i3lock -i ~/.local/share/backgrounds/default --nofork
fi
