# general omz setup
unsetopt nomatch
export ZSH="${HOME}/.config/oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
TERM='xterm-256color'
DEFAULT_USER=$USER
DISABLE_UPDATE_PROMPT=true
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
ZLE_RPROMPT_INDENT=0
DISABLE_MAGIC_FUNCTIONS=true
ZVM_CURSOR_STYLE_ENABLED=false
SHELL_DOT_DIR="${HOME}/.dotfiles/zsh"
plugins=(vi-mode git aws docker)
wanted_custom_plugins=(
    zsh-syntax-highlighting
    zsh-autosuggestions
)
# load all found ZSH plugins
for wanted_plugin in "${wanted_custom_plugins[@]}"; do
    [[ -d "$ZSH/custom/plugins/${wanted_plugin}" ]] && plugins+=(${wanted_plugin})
done
source $ZSH/oh-my-zsh.sh

# load all ZSH-related config files from unified directory
for config in ${SHELL_DOT_DIR}/*.zsh ; do
    source "$config"
done

# load any local ZSH-related config files
for local_config in ${SHELL_DOT_DIR}/local/*.zsh ; do
    source "$local_config"
done

# Dirty hacks
# make color of other-writable directories less offensive
if [[ -f "${SHELL_DOT_DIR}/dircolors" ]]; then
    eval "$(dircolors -b "${SHELL_DOT_DIR}/dircolors" )"
    zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
fi
