FROM alpine:latest

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ARG DOTFILES_MACHINE_TYPE=headless
ARG DOTFILES_INSTALL_HEAVY_DEV=false
ARG DOTFILES_TESTING=true

RUN apk add ca-certificates curl git bash sudo
RUN adduser -D -s /bin/bash testuser \
    && adduser testuser wheel \
    && sed -e 's;^# \(%wheel.*NOPASSWD.*\);\1;g' -i /etc/sudoers

COPY --chown=testuser:testuser . /home/testuser/.dotfiles

USER testuser
WORKDIR /home/testuser
ENV PATH=/home/testuser/.local/bin:$PATH

RUN DOTFILES_MACHINE_TYPE=${DOTFILES_MACHINE_TYPE} \
    DOTFILES_INSTALL_HEAVY_DEV=${DOTFILES_INSTALL_HEAVY_DEV} \
    DOTFILES_TESTING=${DOTFILES_TESTING} \
    DOTFILES_SYSTEM_PACKAGE_MANAGER=apk \
    /home/testuser/.dotfiles/scripts/01_meta/01_setup/bootstrap.sh
