FROM ubuntu:24.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Etc/UTC

ARG DOTFILES_MACHINE_TYPE=headless
ARG DOTFILES_INSTALL_HEAVY_DEV=false
ARG DOTFILES_ALLOW_SUDO=false
ARG DOTFILES_TESTING=true

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update --fix-missing \
    && apt-get install --yes ca-certificates curl git make neovim tmux zsh \
    && apt-get clean

RUN useradd -m testuser -s /bin/bash

COPY --chown=testuser:testuser . /home/testuser/.dotfiles

USER testuser
WORKDIR /home/testuser
ENV PATH=/home/testuser/.local/bin:$PATH

RUN DOTFILES_MACHINE_TYPE=${DOTFILES_MACHINE_TYPE} \
    DOTFILES_INSTALL_HEAVY_DEV=${DOTFILES_INSTALL_HEAVY_DEV} \
    DOTFILES_ALLOW_SUDO=${DOTFILES_ALLOW_SUDO} \
    DOTFILES_TESTING=${DOTFILES_TESTING} \
    /home/testuser/.dotfiles/scripts/01_meta/01_setup/bootstrap.sh

RUN bash -lc 'source ~/.local/share/nvm/nvm.sh && node --version && npm --version && ~/.local/bin/uv --version'
