FROM archlinux:latest

ADD . /opt/envsetup-lite

ARG INSTALL_VARIOUS=true
ARG INSTALL_DESKTOP=false
ARG INSTALL_WORK=false
ARG SYSTEM_PACKAGE_MANAGER=pacman

RUN pacman -Syu --noconfirm which curl sudo
RUN useradd -m testuser -s /bin/bash \
    && echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER testuser
RUN whoami
RUN sudo whoami
WORKDIR /home/testuser

COPY ../../../../ /opt/dotfiles
RUN cp -r /opt/dotfiles ~/.dotfiles; rm ~/.dotfiles/scripts/01_meta/01_setup/.*_done || true
RUN ~/.dotfiles/scripts/01_meta/01_setup/01_setup_all.sh
