FROM archlinux:latest

ADD . /opt/envsetup-lite

ARG INSTALL_VARIOUS=true
ARG INSTALL_DESKTOP=false
ARG INSTALL_WORK=false
ARG DOTFILES_TESTING=true
ARG SYSTEM_PACKAGE_MANAGER=pacman

RUN pacman -Syu --noconfirm which curl sudo
RUN useradd -m testuser -s /bin/bash \
    && echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER testuser
RUN whoami
RUN sudo whoami
WORKDIR /home/testuser

COPY ../../../../ /opt/dotfiles

RUN cp -r /opt/dotfiles ~/.dotfiles || true; \
    rm ~/.dotfiles/scripts/01_meta/01_setup/.*_done \
    && cp ~/.dotfiles/scripts/01_meta/01_setup/tests/condarc /home/testuser/.condarc \
    && mkdir -p /home/testuser/.cache/conda

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/home/testuser/.cache/pip,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/testuser/.cache/conda,uid=1000,gid=1000 \
   ~/.dotfiles/scripts/01_meta/01_setup/05_setup_conda.sh

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/home/testuser/.cache/pip,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/testuser/.cache/conda,uid=1000,gid=1000 \
   ~/.dotfiles/scripts/01_meta/01_setup/07_install_packages.sh

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/home/testuser/.cache/pip,uid=1000,gid=1000 \
    --mount=type=cache,target=/home/testuser/.cache/conda,uid=1000,gid=1000 \
   ~/.dotfiles/scripts/01_meta/01_setup/10_setup_env.sh
