#!/data/data/com.termux/files/usr/bin/zsh
source $HOME/.dotfiles/zsh/functions.zsh
scp rpi3:"$(ssh rpi3-local "$(typeset -f get-newest); get-newest /tmp/rpicam-*/*")" $TMPDIR/cat_trap_latest.png && termux-open $TMPDIR/cat_trap_latest.png
